import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "zh" | "en" | "ja";

const translations = {
  // App
  appName: { zh: "SignCMS Enterprise", en: "SignCMS Enterprise", ja: "SignCMS Enterprise" },
  appSubtitle: { zh: "SignCMS Enterprise", en: "SignCMS Enterprise", ja: "SignCMS Enterprise" },

  // Nav
  navDashboard: { zh: "總覽儀表板", en: "Dashboard", ja: "ダッシュボード" },
  navScreens: { zh: "螢幕管理", en: "Screens", ja: "スクリーン管理" },
  navMedia: { zh: "廣告素材庫", en: "Media Library", ja: "メディアライブラリ" },
  navSchedules: { zh: "播放清單排程", en: "Schedules", ja: "スケジュール" },
  navPublishing: { zh: "發佈管理", en: "Publishing Center", ja: "配信管理" },
  navDeviceLogs: { zh: "系統紀錄", en: "System Logs", ja: "システムログ" },
  navIoTDashboard: { zh: "IoT 監控", en: "IoT Monitor", ja: "IoT モニター" },
  navAdmin: { zh: "使用者管理", en: "User Management", ja: "ユーザー管理" },
  navAppStore: { zh: "擴充應用商店", en: "App Store", ja: "アプリストア" },

  // Common
  cancel: { zh: "取消", en: "Cancel", ja: "キャンセル" },
  save: { zh: "儲存", en: "Save", ja: "保存" },
  delete: { zh: "刪除", en: "Delete", ja: "削除" },
  edit: { zh: "編輯", en: "Edit", ja: "編集" },
  add: { zh: "新增", en: "Add", ja: "追加" },
  search: { zh: "搜尋", en: "Search", ja: "検索" },
  upload: { zh: "上傳", en: "Upload", ja: "アップロード" },
  logout: { zh: "登出", en: "Sign Out", ja: "ログアウト" },
  user: { zh: "使用者", en: "User", ja: "ユーザー" },
  online: { zh: "在線", en: "Online", ja: "オンライン" },
  offline: { zh: "離線", en: "Offline", ja: "オフライン" },
  enabled: { zh: "啟用中", en: "Enabled", ja: "有効" },
  disabled: { zh: "已停用", en: "Disabled", ja: "無効" },
  confirmDelete: { zh: "確定刪除", en: "Confirm Delete", ja: "削除確認" },
  seconds: { zh: "秒", en: "s", ja: "秒" },
  allGroups: { zh: "所有群組", en: "All Groups", ja: "全グループ" },
  allTypes: { zh: "所有類型", en: "All Types", ja: "全タイプ" },
  image: { zh: "圖片", en: "Image", ja: "画像" },
  video: { zh: "影片", en: "Video", ja: "動画" },
  uploadMedia: { zh: "上傳素材", en: "Upload Media", ja: "メディアアップロード" },

  // Dashboard
  dashTitle: { zh: "總覽儀表板", en: "Dashboard", ja: "ダッシュボード" },
  dashSubtitle: { zh: "即時監控所有群組電子看板狀態", en: "Monitor all group digital signage in real-time", ja: "全グループのデジタルサイネージをリアルタイム監視" },
  dashOnlineScreens: { zh: "在線螢幕", en: "Online Screens", ja: "オンラインスクリーン" },
  dashRunningNormal: { zh: "運行正常", en: "Running normally", ja: "正常稼働中" },
  dashOfflineWarning: { zh: "離線螢幕警告", en: "Offline Warnings", ja: "オフライン警告" },
  dashNeedCheck: { zh: "需要檢查", en: "Needs attention", ja: "要確認" },
  dashTodayPlays: { zh: "今日預計播放", en: "Today's Plays", ja: "本日再生予定" },
  dashPlayCount: { zh: "次廣告輪播", en: "ad rotations", ja: "回広告ローテーション" },
  dashScreenList: { zh: "群組螢幕列表", en: "Group Screen List", ja: "グループスクリーン一覧" },
  dashJustNow: { zh: "剛剛", en: "Just now", ja: "たった今" },
  dashMinAgo: { zh: "分鐘前", en: "min ago", ja: "分前" },
  dashScheduleOverview: { zh: "排程總覽", en: "Schedule Overview", ja: "スケジュール概要" },
  dashMediaStats: { zh: "素材使用統計", en: "Media Usage", ja: "メディア使用統計" },
  dashScheduleName: { zh: "排程名稱", en: "Schedule", ja: "スケジュール名" },
  dashItems: { zh: "素材數", en: "Items", ja: "素材数" },
  dashDuration: { zh: "時長(秒)", en: "Duration(s)", ja: "時間(秒)" },
  dashStatus: { zh: "狀態", en: "Status", ja: "ステータス" },
  dashScreen: { zh: "螢幕", en: "Screen", ja: "スクリーン" },
  dashUsedIn: { zh: "次", en: "times", ja: "回" },
  dashTotalMedia: { zh: "素材總數", en: "Total Media", ja: "メディア合計" },
  dashTotalSchedules: { zh: "啟用排程", en: "Active Schedules", ja: "有効スケジュール" },
  dashByType: { zh: "素材類型分佈", en: "Media by Type", ja: "メディアタイプ分布" },
  dashByBranch: { zh: "各群組螢幕數", en: "Screens by Group", ja: "グループ別スクリーン数" },

  // Screens
  screensTitle: { zh: "螢幕管理", en: "Screen Management", ja: "スクリーン管理" },
  screensSubtitle: { zh: "管理所有群組的電子看板設備", en: "Manage all group digital signage devices", ja: "全グループのデジタルサイネージを管理" },
  screensAdd: { zh: "新增螢幕", en: "Add Screen", ja: "スクリーン追加" },
  screensSearchPlaceholder: { zh: "搜尋螢幕名稱、群組...", en: "Search screens, groups...", ja: "スクリーン名、グループを検索..." },
  screensNoResult: { zh: "沒有找到符合條件的螢幕", en: "No screens found", ja: "スクリーンが見つかりません" },
  screensName: { zh: "螢幕名稱", en: "Screen Name", ja: "スクリーン名" },
  screensBranch: { zh: "所屬群組", en: "Group", ja: "所属グループ" },
  screensLocation: { zh: "安裝位置", en: "Location", ja: "設置場所" },
  screensResolution: { zh: "螢幕解析度", en: "Resolution", ja: "解像度" },
  screensEditTitle: { zh: "編輯螢幕", en: "Edit Screen", ja: "スクリーン編集" },
  screensAddTitle: { zh: "新增螢幕", en: "Add Screen", ja: "スクリーン追加" },
  screensSaveChanges: { zh: "儲存變更", en: "Save Changes", ja: "変更を保存" },
  screensDeleteConfirm: { zh: "確定要刪除這台螢幕嗎？", en: "Delete this screen?", ja: "このスクリーンを削除しますか？" },
  screensDeleteDesc: { zh: "刪除後將無法復原，相關的播放排程也會一併移除。", en: "This action cannot be undone. Related schedules will also be removed.", ja: "この操作は取り消せません。関連するスケジュールも削除されます。" },
  screensSelectBranch: { zh: "選擇群組", en: "Select group", ja: "グループを選択" },
  screensNamePlaceholder: { zh: "例如：1F 入口大螢幕", en: "e.g. 1F Entrance Display", ja: "例：1F 入口ディスプレイ" },
  screensLocationPlaceholder: { zh: "例如：一樓入口右側", en: "e.g. Right side of 1F entrance", ja: "例：1階入口右側" },
  screensFillRequired: { zh: "請填寫螢幕名稱和所屬群組", en: "Please fill in screen name and group", ja: "スクリーン名と所属グループを入力してください" },
  screensNewGroup: { zh: "新增群組", en: "New Group", ja: "新規グループ" },
  screensNewGroupPlaceholder: { zh: "輸入新群組名稱", en: "Enter new group name", ja: "新しいグループ名を入力" },
  screensGroupCreated: { zh: "群組已建立", en: "Group created", ja: "グループを作成しました" },
  screensManageGroups: { zh: "管理群組", en: "Manage Groups", ja: "グループ管理" },
  screensDeleteGroup: { zh: "刪除群組", en: "Delete Group", ja: "グループ削除" },
  screensDeleteGroupDesc: { zh: "刪除群組後，群組內的螢幕將變為「未分類」。", en: "Screens in this group will become ungrouped.", ja: "グループ内のスクリーンは「未分類」になります。" },
  screensUngrouped: { zh: "未分類", en: "Uncategorized", ja: "未分類" },
  screensRenameGroup: { zh: "重新命名群組", en: "Rename Group", ja: "グループ名変更" },
  screensRenameGroupPlaceholder: { zh: "輸入新的群組名稱", en: "Enter new group name", ja: "新しいグループ名を入力" },
  screensGroupRenamed: { zh: "群組已重新命名", en: "Group renamed", ja: "グループ名を変更しました" },
  screensGroupDeleted: { zh: "群組已刪除", en: "Group deleted", ja: "グループを削除しました" },
  screensGroupExists: { zh: "群組已存在", en: "Group already exists", ja: "グループは既に存在します" },
  screensUpdated: { zh: "螢幕已更新", en: "Screen updated", ja: "スクリーンを更新しました" },
  screensAdded: { zh: "螢幕已新增", en: "Screen added", ja: "スクリーンを追加しました" },
  screensDeleted: { zh: "螢幕已刪除", en: "Screen deleted", ja: "スクリーンを削除しました" },

  // Screen Settings
  screenSettings: { zh: "螢幕設定", en: "Screen Settings", ja: "スクリーン設定" },
  screenSettingsNetwork: { zh: "網路連線設定", en: "Network Settings", ja: "ネットワーク設定" },
  screenSettingsIpMode: { zh: "IP 模式", en: "IP Mode", ja: "IPモード" },
  screenSettingsDhcp: { zh: "DHCP (自動取得)", en: "DHCP (Auto)", ja: "DHCP（自動）" },
  screenSettingsStatic: { zh: "固定 IP", en: "Static IP", ja: "固定IP" },
  screenSettingsIpAddress: { zh: "IP 位址", en: "IP Address", ja: "IPアドレス" },
  screenSettingsSubnet: { zh: "子網路遮罩", en: "Subnet Mask", ja: "サブネットマスク" },
  screenSettingsGateway: { zh: "預設閘道", en: "Gateway", ja: "ゲートウェイ" },
  screenSettingsDns: { zh: "DNS 伺服器", en: "DNS Server", ja: "DNSサーバー" },
  screenSettingsNtp: { zh: "NTP 伺服器", en: "NTP Server", ja: "NTPサーバー" },
  screenSettingsRotation: { zh: "螢幕旋轉方向", en: "Screen Rotation", ja: "画面回転" },
  screenSettingsRotation0: { zh: "0° (標準)", en: "0° (Normal)", ja: "0°（標準）" },
  screenSettingsRotation90: { zh: "90° (順時針)", en: "90° (CW)", ja: "90°（時計回り）" },
  screenSettingsRotation180: { zh: "180° (倒轉)", en: "180° (Inverted)", ja: "180°（反転）" },
  screenSettingsRotation270: { zh: "270° (逆時針)", en: "270° (CCW)", ja: "270°（反時計回り）" },
  screenSettingsScheduleOnOff: { zh: "排程開關機", en: "Schedule On/Off", ja: "スケジュールON/OFF" },
  screenSettingsScheduleOn: { zh: "開機時間", en: "Power On Time", ja: "起動時刻" },
  screenSettingsScheduleOff: { zh: "關機時間", en: "Power Off Time", ja: "シャットダウン時刻" },
  screenSettingsReboot: { zh: "立即重新開機", en: "Reboot Now", ja: "今すぐ再起動" },
  screenSettingsRebootConfirm: { zh: "確定要立即重新開機嗎？", en: "Reboot this screen now?", ja: "今すぐ再起動しますか？" },
  screenSettingsRebootDesc: { zh: "螢幕將立即重新啟動，播放中的內容會暫時中斷。", en: "The screen will restart immediately. Currently playing content will be interrupted.", ja: "スクリーンが即座に再起動されます。再生中のコンテンツは中断されます。" },
  screenSettingsSaved: { zh: "螢幕設定已儲存", en: "Screen settings saved", ja: "スクリーン設定を保存しました" },
  screenSettingsRebooting: { zh: "已發送重新開機指令", en: "Reboot command sent", ja: "再起動コマンドを送信しました" },
  screenLiveView: { zh: "遠端監視", en: "Live View", ja: "ライブビュー" },
  screenLiveViewPlaceholder: { zh: "遠端監視功能開發中", en: "Live View coming soon", ja: "ライブビュー機能は開発中です" },
  screenDefaultPlayback: { zh: "無排程預設播放", en: "Default Playback", ja: "デフォルト再生" },
  screenDefaultPlaybackDesc: { zh: "當螢幕沒有排程播放時的預設行為", en: "Default behavior when no schedule is active", ja: "スケジュールがないときのデフォルト動作" },
  screenDefaultSleep: { zh: "螢幕休眠", en: "Screen Sleep", ja: "スクリーンスリープ" },
  screenDefaultMedia: { zh: "播放素材", en: "Play Media", ja: "メディア再生" },
  screenDefaultDesign: { zh: "播放內容設計專案", en: "Play Content Design", ja: "コンテンツデザイン再生" },
  screenDefaultSelectMedia: { zh: "選擇素材", en: "Select Media", ja: "メディアを選択" },
  screenDefaultSelectProject: { zh: "選擇內容設計專案", en: "Select Content Design", ja: "コンテンツデザインを選択" },

  // Media
  mediaTitle: { zh: "廣告素材庫", en: "Media Library", ja: "メディアライブラリ" },
  mediaSubtitle: { zh: "管理所有廣告圖片與影片素材", en: "Manage all advertising images and videos", ja: "すべての広告画像と動画を管理" },
  mediaImages: { zh: "張圖片", en: "images", ja: "枚の画像" },
  mediaVideos: { zh: "部影片", en: "videos", ja: "本の動画" },
  mediaSearchPlaceholder: { zh: "搜尋素材名稱...", en: "Search media...", ja: "メディアを検索..." },
  mediaNoResult: { zh: "沒有找到符合條件的素材", en: "No media found", ja: "メディアが見つかりません" },
  mediaUpload: { zh: "上傳素材", en: "Upload Media", ja: "メディアアップロード" },
  mediaDeleteConfirm: { zh: "確定要刪除這個素材嗎？", en: "Delete this media?", ja: "このメディアを削除しますか？" },
  mediaDeleteDesc: { zh: "刪除後將無法復原，使用此素材的播放清單也會受到影響。", en: "This cannot be undone. Playlists using this media will be affected.", ja: "この操作は取り消せません。このメディアを使用するプレイリストに影響します。" },
  mediaCheckingUsage: { zh: "檢查使用狀態中...", en: "Checking usage...", ja: "使用状況を確認中..." },
  mediaInUseWarning: { zh: "此素材正在使用中，無法刪除。請先從以下位置移除後再刪除。", en: "This media is in use and cannot be deleted. Remove it from the following first.", ja: "このメディアは使用中のため削除できません。先に以下から削除してください。" },
  mediaUsedInProjects: { zh: "設計專案", en: "Design Projects", ja: "デザインプロジェクト" },
  mediaUsedInSchedules: { zh: "播放清單排程", en: "Schedules", ja: "スケジュール" },
  mediaType: { zh: "類型", en: "Type", ja: "タイプ" },
  mediaFileSize: { zh: "檔案大小", en: "File Size", ja: "ファイルサイズ" },
  mediaFileName: { zh: "檔案名稱", en: "File Name", ja: "ファイル名" },
  mediaEncoding: { zh: "編碼格式", en: "Encoding", ja: "エンコード" },
  mediaResolution: { zh: "解析度", en: "Resolution", ja: "解像度" },
  mediaDuration: { zh: "時長", en: "Duration", ja: "再生時間" },
  mediaPixels: { zh: "畫素", en: "Pixels", ja: "画素数" },
  mediaFrameRate: { zh: "幀率", en: "Frame Rate", ja: "フレームレート" },
  mediaBitrate: { zh: "位元率", en: "Bitrate", ja: "ビットレート" },
  mediaUploadDate: { zh: "上傳日期", en: "Upload Date", ja: "アップロード日" },
  mediaPreviewUnavailable: { zh: "預覽不可用（範例素材）", en: "Preview unavailable (sample)", ja: "プレビュー不可（サンプル）" },
  mediaDeleteItem: { zh: "刪除素材", en: "Delete Media", ja: "メディア削除" },
  mediaUploaded: { zh: "已上傳", en: "Uploaded", ja: "アップロード済み" },
  mediaDeleted: { zh: "已刪除", en: "Deleted", ja: "削除済み" },
  mediaUnsupported: { zh: "不支援的檔案格式", en: "Unsupported file format", ja: "サポートされていないファイル形式" },
  mediaFileTooLarge: { zh: "檔案大小超過限制（最大 50 MB）", en: "File too large (max 50 MB)", ja: "ファイルが大きすぎます（最大 50 MB）" },
  mediaReading: { zh: "讀取中...", en: "Loading...", ja: "読み込み中..." },
  mediaProjectGroup: { zh: "設計專案", en: "Project Group", ja: "デザインプロジェクト" },
  mediaAllProjects: { zh: "全部專案", en: "All Projects", ja: "全プロジェクト" },
  mediaNoProject: { zh: "未分類", en: "Uncategorized", ja: "未分類" },
  mediaUploadToProject: { zh: "上傳至專案", en: "Upload to Project", ja: "プロジェクトにアップロード" },
  mediaManageProjects: { zh: "管理專案", en: "Manage Projects", ja: "プロジェクト管理" },
  mediaAddProject: { zh: "新增專案", en: "Add Project", ja: "プロジェクト追加" },
  mediaProjectName: { zh: "專案名稱", en: "Project Name", ja: "プロジェクト名" },
  mediaProjectNamePlaceholder: { zh: "輸入專案名稱", en: "Enter project name", ja: "プロジェクト名を入力" },
  mediaProjectCreated: { zh: "專案已建立", en: "Project created", ja: "プロジェクトを作成しました" },
  mediaProjectUpdated: { zh: "專案已更新", en: "Project updated", ja: "プロジェクトを更新しました" },
  mediaProjectDeleted: { zh: "專案已刪除", en: "Project deleted", ja: "プロジェクトを削除しました" },
  mediaProjectDeleteConfirm: { zh: "確定要刪除此專案？該專案下的素材將變為未分類。", en: "Delete this project? Media items in it will become uncategorized.", ja: "このプロジェクトを削除しますか？所属メディアは未分類になります。" },
  widget: { zh: "Widget", en: "Widget", ja: "ウィジェット" },
  mediaWidgets: { zh: "個 Widget", en: "widgets", ja: "個のウィジェット" },
  mediaAddWidget: { zh: "新增 Widget", en: "Add Widget", ja: "ウィジェット追加" },
  widgetSystem: { zh: "系統", en: "System", ja: "システム" },
  widgetRegular: { zh: "一般", en: "Regular", ja: "一般" },
  widgetSystemCannotDelete: { zh: "系統 Widget 無法刪除", en: "System widgets cannot be deleted", ja: "システムウィジェットは削除できません" },
  widgetDate: { zh: "日期", en: "Date", ja: "日付" },
  widgetClock: { zh: "時鐘", en: "Clock", ja: "時計" },
  widgetWebpage: { zh: "網頁", en: "Webpage", ja: "ウェブページ" },
  widgetMarquee: { zh: "跑馬燈", en: "Marquee", ja: "テロップ" },
  widgetQrcode: { zh: "QR Code", en: "QR Code", ja: "QRコード" },
  widgetCountdown: { zh: "倒數計時", en: "Countdown", ja: "カウントダウン" },
  widgetYoutube: { zh: "YouTube", en: "YouTube", ja: "YouTube" },
  widgetWeather: { zh: "天氣預報", en: "Weather", ja: "天気予報" },
  widgetDateDesc: { zh: "顯示當前日期", en: "Display current date", ja: "現在の日付を表示" },
  widgetClockDesc: { zh: "顯示即時時鐘", en: "Display real-time clock", ja: "リアルタイム時計を表示" },
  widgetWebpageDesc: { zh: "嵌入指定網頁內容", en: "Embed a webpage", ja: "指定のウェブページを埋め込む" },
  widgetMarqueeDesc: { zh: "滾動文字跑馬燈", en: "Scrolling text marquee", ja: "スクロールテキストテロップ" },
  widgetQrcodeDesc: { zh: "輸入網址或文字產生 QR Code", en: "Generate QR code from URL or text", ja: "URLやテキストからQRコードを生成" },
  widgetCountdownDesc: { zh: "設定目標日期倒數計時", en: "Countdown to a target date", ja: "目標日までカウントダウン" },
  widgetYoutubeDesc: { zh: "嵌入 YouTube 影片播放", en: "Embed YouTube video", ja: "YouTube動画を埋め込む" },
  widgetWeatherDesc: { zh: "顯示指定城市天氣資訊", en: "Display weather for a city", ja: "指定都市の天気を表示" },
  widgetName: { zh: "Widget 名稱", en: "Widget Name", ja: "ウィジェット名" },
  widgetNamePlaceholder: { zh: "例如：大廳時鐘", en: "e.g. Lobby Clock", ja: "例：ロビー時計" },
  widgetType: { zh: "Widget 類型", en: "Widget Type", ja: "ウィジェットタイプ" },
  widgetUrl: { zh: "網頁網址", en: "Webpage URL", ja: "ウェブページURL" },
  widgetUrlPlaceholder: { zh: "https://example.com", en: "https://example.com", ja: "https://example.com" },
  widgetText: { zh: "跑馬燈文字", en: "Marquee Text", ja: "テロップテキスト" },
  widgetTextPlaceholder: { zh: "輸入滾動文字內容...", en: "Enter scrolling text...", ja: "スクロールテキストを入力..." },
  widgetSpeed: { zh: "捲動速度", en: "Scroll Speed", ja: "スクロール速度" },
  widgetSpeedSlow: { zh: "慢", en: "Slow", ja: "遅い" },
  widgetSpeedNormal: { zh: "中", en: "Normal", ja: "普通" },
  widgetSpeedFast: { zh: "快", en: "Fast", ja: "速い" },
  widgetFormat: { zh: "顯示格式", en: "Display Format", ja: "表示形式" },
  widgetFormat12: { zh: "12小時制", en: "12-hour", ja: "12時間制" },
  widgetFormat24: { zh: "24小時制", en: "24-hour", ja: "24時間制" },
  widgetBgColor: { zh: "背景顏色", en: "Background Color", ja: "背景色" },
  widgetTextColor: { zh: "文字顏色", en: "Text Color", ja: "テキスト色" },
  widgetCreated: { zh: "Widget 已建立", en: "Widget created", ja: "ウィジェットを作成しました" },
  widgetClockStyle: { zh: "時鐘樣式", en: "Clock Style", ja: "時計スタイル" },
  widgetDigital: { zh: "數位時鐘", en: "Digital", ja: "デジタル" },
  widgetAnalog: { zh: "類比時鐘", en: "Analog", ja: "アナログ" },
  widgetTimezone: { zh: "時區", en: "Timezone", ja: "タイムゾーン" },
  widgetShowDate: { zh: "顯示日期", en: "Show Date", ja: "日付を表示" },
  widgetFillRequired: { zh: "請填寫 Widget 名稱", en: "Please fill in widget name", ja: "ウィジェット名を入力してください" },
  widgetQrcodeContent: { zh: "QR Code 內容", en: "QR Code Content", ja: "QRコード内容" },
  widgetQrcodePlaceholder: { zh: "輸入網址或文字...", en: "Enter URL or text...", ja: "URLまたはテキストを入力..." },
  widgetTargetDate: { zh: "目標日期", en: "Target Date", ja: "目標日" },
  widgetCountdownTitle: { zh: "倒數標題", en: "Countdown Title", ja: "カウントダウンタイトル" },
  widgetCountdownTitlePlaceholder: { zh: "例如：新品上市倒數", en: "e.g. Product Launch", ja: "例：新商品発売" },
  widgetYoutubeUrl: { zh: "YouTube 網址", en: "YouTube URL", ja: "YouTube URL" },
  widgetYoutubeUrlPlaceholder: { zh: "https://www.youtube.com/watch?v=...", en: "https://www.youtube.com/watch?v=...", ja: "https://www.youtube.com/watch?v=..." },
  widgetCity: { zh: "城市名稱", en: "City Name", ja: "都市名" },
  widgetCityPlaceholder: { zh: "例如：Taipei", en: "e.g. London", ja: "例：Tokyo" },
  widgetDays: { zh: "天", en: "days", ja: "日" },
  widgetHours: { zh: "時", en: "hrs", ja: "時間" },
  widgetMinutes: { zh: "分", en: "min", ja: "分" },
  widgetSeconds: { zh: "秒", en: "sec", ja: "秒" },
  widgetFontSize: { zh: "字體大小", en: "Font Size", ja: "フォントサイズ" },
  widgetFontSizeSmall: { zh: "小", en: "Small", ja: "小" },
  widgetFontSizeMedium: { zh: "中", en: "Medium", ja: "中" },
  widgetFontSizeLarge: { zh: "大", en: "Large", ja: "大" },
  widgetFontSizeXLarge: { zh: "特大", en: "Extra Large", ja: "特大" },
  widgetQrcodeSize: { zh: "QR Code 大小", en: "QR Code Size", ja: "QRコードサイズ" },
  widgetAnimation: { zh: "入場動畫", en: "Entrance Animation", ja: "入場アニメーション" },
  widgetAnimNone: { zh: "無", en: "None", ja: "なし" },
  widgetAnimFadeIn: { zh: "淡入", en: "Fade In", ja: "フェードイン" },
  widgetAnimSlideUp: { zh: "上滑", en: "Slide Up", ja: "スライドアップ" },
  widgetAnimBounce: { zh: "彈跳", en: "Bounce", ja: "バウンス" },
  widgetAnimZoomIn: { zh: "放大", en: "Zoom In", ja: "ズームイン" },
  widgetAnimFlipIn: { zh: "翻轉", en: "Flip In", ja: "フリップイン" },
  widgetLivePreview: { zh: "即時預覽", en: "Live Preview", ja: "ライブプレビュー" },

  // Schedules
  schedTitle: { zh: "播放清單排程", en: "Playlist Schedules", ja: "プレイリストスケジュール" },
  schedSubtitle: { zh: "設定各螢幕的播放內容與時段", en: "Configure playback content and time slots for each screen", ja: "各スクリーンの再生内容と時間帯を設定" },
  schedAdd: { zh: "新增排程", en: "Add Schedule", ja: "スケジュール追加" },
  schedNoResult: { zh: "尚未建立任何排程", en: "No schedules created yet", ja: "スケジュールはまだありません" },
  schedName: { zh: "排程名稱", en: "Schedule Name", ja: "スケジュール名" },
  schedScreen: { zh: "指定螢幕", en: "Target Screen", ja: "対象スクリーン" },
  schedStartTime: { zh: "開始時間", en: "Start Time", ja: "開始時間" },
  schedEndTime: { zh: "結束時間", en: "End Time", ja: "終了時間" },
  schedPlayDays: { zh: "播放日", en: "Play Days", ja: "再生日" },
  schedPlaylist: { zh: "播放清單", en: "Playlist", ja: "プレイリスト" },
  schedPlayOrder: { zh: "播放順序", en: "Play Order", ja: "再生順序" },
  schedItems: { zh: "個素材", en: "items", ja: "アイテム" },
  schedSelectScreen: { zh: "選擇螢幕", en: "Select screen", ja: "スクリーンを選択" },
  schedNamePlaceholder: { zh: "例如：早班輪播", en: "e.g. Morning rotation", ja: "例：朝のローテーション" },
  schedFillRequired: { zh: "請填寫排程名稱和指定螢幕", en: "Please fill in schedule name and target screen", ja: "スケジュール名と対象スクリーンを入力してください" },
  schedAddItem: { zh: "請至少加入一個素材", en: "Add at least one media item", ja: "少なくとも1つのメディアを追加してください" },
  schedUpdated: { zh: "排程已更新", en: "Schedule updated", ja: "スケジュールを更新しました" },
  schedAdded: { zh: "排程已新增", en: "Schedule added", ja: "スケジュールを追加しました" },
  schedDeleted: { zh: "排程已刪除", en: "Schedule deleted", ja: "スケジュールを削除しました" },
  schedEditTitle: { zh: "編輯排程", en: "Edit Schedule", ja: "スケジュール編集" },
  schedAddTitle: { zh: "新增排程", en: "Add Schedule", ja: "スケジュール追加" },
  schedSaveChanges: { zh: "儲存變更", en: "Save Changes", ja: "変更を保存" },
  schedDeleteConfirm: { zh: "確定要刪除這個排程嗎？", en: "Delete this schedule?", ja: "このスケジュールを削除しますか？" },
  schedDeleteDesc: { zh: "刪除後將無法復原，該螢幕的播放內容將會停止。", en: "This cannot be undone. Playback on this screen will stop.", ja: "この操作は取り消せません。このスクリーンの再生は停止します。" },
  schedClickToAdd: { zh: "點擊加入素材", en: "Click to add media", ja: "クリックしてメディアを追加" },
  schedFromBelow: { zh: "從下方選擇素材、設計專案或 Widget 加入清單", en: "Select media, design projects or widgets below to add to playlist", ja: "下からメディア、デザインプロジェクト、またはウィジェットを選択してプレイリストに追加" },
  schedTabMedia: { zh: "素材", en: "Media", ja: "メディア" },
  schedTabDesign: { zh: "設計專案", en: "Design Projects", ja: "デザイン" },
  schedTabWidget: { zh: "Widget", en: "Widgets", ja: "ウィジェット" },

  // Days
  dayMon: { zh: "一", en: "Mon", ja: "月" },
  dayTue: { zh: "二", en: "Tue", ja: "火" },
  dayWed: { zh: "三", en: "Wed", ja: "水" },
  dayThu: { zh: "四", en: "Thu", ja: "木" },
  dayFri: { zh: "五", en: "Fri", ja: "金" },
  daySat: { zh: "六", en: "Sat", ja: "土" },
  daySun: { zh: "日", en: "Sun", ja: "日" },

  // Duration formatting
  durationMin: { zh: "分", en: "m", ja: "分" },
  durationSec: { zh: "秒", en: "s", ja: "秒" },

  // Admin
  adminTitle: { zh: "使用者管理", en: "User Management", ja: "ユーザー管理" },
  adminSubtitle: { zh: "管理系統使用者角色與權限", en: "Manage user roles and permissions", ja: "ユーザーの役割と権限を管理" },
  adminTotalUsers: { zh: "總使用者數", en: "Total Users", ja: "総ユーザー数" },
  adminAdminCount: { zh: "管理員數", en: "Admin Count", ja: "管理者数" },
  adminUserList: { zh: "使用者列表", en: "User List", ja: "ユーザー一覧" },
  adminUserListDesc: { zh: "查看和管理所有使用者的角色", en: "View and manage all user roles", ja: "すべてのユーザーの役割を表示・管理" },
  adminRole: { zh: "管理員", en: "Admin", ja: "管理者" },
  adminRegularUser: { zh: "一般使用者", en: "Regular User", ja: "一般ユーザー" },
  adminUnnamed: { zh: "未命名使用者", en: "Unnamed User", ja: "未設定ユーザー" },
  adminConfirmChange: { zh: "確認更改角色", en: "Confirm Role Change", ja: "役割変更の確認" },
  adminConfirmChangeDesc: { zh: "確定要將", en: "Are you sure you want to change", ja: "次のユーザーの役割を変更しますか：" },
  adminChangeRoleTo: { zh: "的角色更改為", en: "'s role to", ja: "の役割を" },
  adminConfirm: { zh: "確認更改", en: "Confirm", ja: "確認" },
  adminNoPermission: { zh: "權限不足", en: "Access Denied", ja: "アクセス拒否" },
  adminNoPermissionDesc: { zh: "您沒有管理員權限，無法存取此頁面。請聯繫系統管理員。", en: "You don't have admin privileges. Contact system administrator.", ja: "管理者権限がありません。システム管理者にお問い合わせください。" },
  adminRoleUpdated: { zh: "角色更新成功", en: "Role updated", ja: "役割を更新しました" },
  adminRoleUpdateFailed: { zh: "角色更新失敗", en: "Role update failed", ja: "役割の更新に失敗しました" },

  // Auth
  authWelcome: { zh: "歡迎回來", en: "Welcome Back", ja: "おかえりなさい" },
  authCreateAccount: { zh: "建立帳號", en: "Create Account", ja: "アカウント作成" },
  authSignUpDesc: { zh: "註冊以開始管理您的電子看板", en: "Sign up to manage your digital signage", ja: "デジタルサイネージの管理を開始" },
  authSignInDesc: { zh: "登入以管理您的電子看板系統", en: "Sign in to manage your digital signage", ja: "デジタルサイネージシステムにログイン" },
  authGoogleSignIn: { zh: "使用 Google 帳號登入", en: "Sign in with Google", ja: "Google でログイン" },
  authOrEmail: { zh: "或使用 Email", en: "or use Email", ja: "またはメールで" },
  authDisplayName: { zh: "顯示名稱", en: "Display Name", ja: "表示名" },
  authNamePlaceholder: { zh: "您的名稱", en: "Your name", ja: "お名前" },
  authPassword: { zh: "密碼", en: "Password", ja: "パスワード" },
  authPasswordPlaceholder: { zh: "至少 6 個字元", en: "At least 6 characters", ja: "6文字以上" },
  authForgotPassword: { zh: "忘記密碼？", en: "Forgot password?", ja: "パスワードを忘れた方" },
  authSignIn: { zh: "登入", en: "Sign In", ja: "ログイン" },
  authSignUp: { zh: "註冊", en: "Sign Up", ja: "新規登録" },
  authHaveAccount: { zh: "已有帳號？", en: "Already have an account?", ja: "アカウントをお持ちの方" },
  authNoAccount: { zh: "還沒有帳號？", en: "Don't have an account?", ja: "アカウントをお持ちでない方" },
  authSignUpSuccess: { zh: "註冊成功！請檢查您的信箱以驗證帳號。", en: "Sign up successful! Check your email to verify.", ja: "登録成功！メールを確認してアカウントを認証してください。" },
  authSignInSuccess: { zh: "登入成功！", en: "Signed in!", ja: "ログインしました！" },
  authFailed: { zh: "驗證失敗，請重試。", en: "Authentication failed. Please try again.", ja: "認証に失敗しました。もう一度お試しください。" },
  authGoogleFailed: { zh: "Google 登入失敗", en: "Google sign-in failed", ja: "Google ログインに失敗しました" },

  // Forgot password
  forgotTitle: { zh: "忘記密碼", en: "Forgot Password", ja: "パスワードを忘れた方" },
  forgotDesc: { zh: "輸入您的 Email，我們將寄送重設連結", en: "Enter your email to receive a reset link", ja: "メールアドレスを入力してリセットリンクを送信" },
  forgotCheckEmail: { zh: "請檢查您的信箱", en: "Check your email", ja: "メールを確認してください" },
  forgotSent: { zh: "重設密碼連結已寄出，請檢查您的信箱。", en: "Reset link sent. Check your email.", ja: "リセットリンクを送信しました。メールを確認してください。" },
  forgotSentDesc: { zh: "我們已將密碼重設連結寄至", en: "We've sent a password reset link to", ja: "パスワードリセットリンクを送信しました：" },
  forgotClickLink: { zh: "，請點擊信中的連結來設定新密碼。", en: ". Click the link in the email to set a new password.", ja: "。メール内のリンクをクリックして新しいパスワードを設定してください。" },
  forgotBackToLogin: { zh: "返回登入", en: "Back to Login", ja: "ログインに戻る" },
  forgotSendLink: { zh: "寄送重設連結", en: "Send Reset Link", ja: "リセットリンクを送信" },
  forgotSendFailed: { zh: "發送失敗，請重試。", en: "Failed to send. Please try again.", ja: "送信に失敗しました。もう一度お試しください。" },

  // Reset password
  resetTitle: { zh: "設定新密碼", en: "Set New Password", ja: "新しいパスワードの設定" },
  resetDesc: { zh: "請輸入您的新密碼", en: "Enter your new password", ja: "新しいパスワードを入力してください" },
  resetNewPassword: { zh: "新密碼", en: "New Password", ja: "新しいパスワード" },
  resetConfirmPassword: { zh: "確認新密碼", en: "Confirm Password", ja: "パスワード確認" },
  resetConfirmPlaceholder: { zh: "再次輸入新密碼", en: "Re-enter new password", ja: "新しいパスワードを再入力" },
  resetUpdate: { zh: "更新密碼", en: "Update Password", ja: "パスワードを更新" },
  resetMismatch: { zh: "兩次密碼輸入不一致", en: "Passwords don't match", ja: "パスワードが一致しません" },
  resetSuccess: { zh: "密碼已更新成功！", en: "Password updated!", ja: "パスワードを更新しました！" },
  resetFailed: { zh: "密碼更新失敗", en: "Password update failed", ja: "パスワードの更新に失敗しました" },
  resetInvalidLink: { zh: "無效的重設連結，請重新請求密碼重設。", en: "Invalid reset link. Please request a new one.", ja: "無効なリセットリンクです。新しいリンクをリクエストしてください。" },
  resetRequestNew: { zh: "重新請求", en: "Request New Link", ja: "新しいリンクをリクエスト" },

  // 404
  notFoundTitle: { zh: "找不到頁面", en: "Page Not Found", ja: "ページが見つかりません" },
  notFoundDesc: { zh: "您訪問的頁面不存在", en: "The page you're looking for doesn't exist", ja: "お探しのページは存在しません" },
  notFoundBack: { zh: "返回首頁", en: "Return to Home", ja: "ホームに戻る" },

  // Theme
  lightMode: { zh: "淺色模式", en: "Light Mode", ja: "ライトモード" },
  darkMode: { zh: "深色模式", en: "Dark Mode", ja: "ダークモード" },

  // Content Studio
  navStudio: { zh: "內容設計中心", en: "Content Studio", ja: "コンテンツスタジオ" },
  studioTitle: { zh: "內容設計中心", en: "Content Studio", ja: "コンテンツスタジオ" },
  studioSubtitle: { zh: "輕鬆設計廣告看板內容", en: "Design signage content with ease", ja: "サイネージコンテンツを簡単デザイン" },
  studioLandscape: { zh: "橫式 16:9", en: "Landscape 16:9", ja: "横型 16:9" },
  studioPortrait: { zh: "直式 9:16", en: "Portrait 9:16", ja: "縦型 9:16" },
  studioLayouts: { zh: "版面分割", en: "Layouts", ja: "レイアウト" },
  studioTemplates: { zh: "樣板庫", en: "Templates", ja: "テンプレート" },
  studioZones: { zh: "個區塊", en: "zones", ja: "ゾーン" },
  studioEditZone: { zh: "編輯區塊", en: "Edit Zone", ja: "ゾーン編集" },
  studioUploadImage: { zh: "上傳圖片", en: "Upload Image", ja: "画像アップロード" },
  studioUploadVideo: { zh: "上傳影片", en: "Upload Video", ja: "動画アップロード" },
  studioText: { zh: "文字內容", en: "Text Content", ja: "テキスト内容" },
  studioTextPlaceholder: { zh: "輸入文字...", en: "Enter text...", ja: "テキストを入力..." },
  studioBgColor: { zh: "背景顏色", en: "Background Color", ja: "背景色" },
  studioLayoutFull: { zh: "全螢幕單一畫面", en: "Full Screen", ja: "フルスクリーン" },
  studioLayoutLR: { zh: "左右分割", en: "Left & Right", ja: "左右分割" },
  studioLayoutTB: { zh: "上下分割 + 跑馬燈", en: "Top + Ticker", ja: "上下分割+テロップ" },
  studioLayoutGrid: { zh: "四宮格", en: "4-Grid", ja: "4分割グリッド" },
  studioTplFood: { zh: "餐飲促銷", en: "Food Promo", ja: "飲食プロモ" },
  studioTplHoliday: { zh: "節日問候", en: "Holiday Greeting", ja: "ホリデー挨拶" },
  studioTplNew: { zh: "新品上市", en: "New Arrival", ja: "新商品" },
  studioTplSummer: { zh: "夏日特惠", en: "Summer Sale", ja: "サマーセール" },
  studioTplGift: { zh: "禮品活動", en: "Gift Event", ja: "ギフトイベント" },
  studioTplCoffee: { zh: "咖啡時光", en: "Coffee Time", ja: "コーヒータイム" },
  studioFontSize: { zh: "字型大小", en: "Font Size", ja: "フォントサイズ" },
  studioTextAlign: { zh: "文字對齊", en: "Text Align", ja: "テキスト配置" },
  studioMediaCarousel: { zh: "媒體輪播", en: "Media Carousel", ja: "メディアカルーセル" },
  studioAddContent: { zh: "新增內容", en: "Add Content", ja: "コンテンツ追加" },
  studioContentPicker: { zh: "媒體與 Widget", en: "Media & Widgets", ja: "メディア＆ウィジェット" },
  studioConfirmAdd: { zh: "確認加入", en: "Confirm", ja: "確認" },
  studioSelectedCount: { zh: "已選 {count} 項", en: "{count} selected", ja: "{count} 件選択" },
  pickerSearchPlaceholder: { zh: "搜尋檔案名稱…", en: "Search by name…", ja: "名前で検索…" },
  pickerFilter_all: { zh: "全部", en: "All", ja: "すべて" },
  pickerFilter_image: { zh: "圖片", en: "Image", ja: "画像" },
  pickerFilter_video: { zh: "影片", en: "Video", ja: "動画" },
  pickerFilter_widget: { zh: "Widget", en: "Widget", ja: "ウィジェット" },
  pickerSort: { zh: "排序", en: "Sort", ja: "並べ替え" },
  "pickerSort_name-asc": { zh: "名稱 A→Z", en: "Name A→Z", ja: "名前 A→Z" },
  "pickerSort_name-desc": { zh: "名稱 Z→A", en: "Name Z→A", ja: "名前 Z→A" },
  pickerSort_newest: { zh: "最新優先", en: "Newest first", ja: "新しい順" },
  pickerSort_oldest: { zh: "最舊優先", en: "Oldest first", ja: "古い順" },
  studioInterval: { zh: "輪播間隔", en: "Interval", ja: "間隔" },
  studioTransition: { zh: "過場效果", en: "Transition", ja: "トランジション" },
  studioTransFade: { zh: "淡入淡出", en: "Fade", ja: "フェード" },
  studioTransSlide: { zh: "滑動切換", en: "Slide", ja: "スライド" },
  studioTransZoom: { zh: "縮放", en: "Zoom", ja: "ズーム" },
  studioTransNone: { zh: "無", en: "None", ja: "なし" },
  studioProjects: { zh: "我的專案", en: "My Projects", ja: "マイプロジェクト" },
  studioNoProjects: { zh: "尚無儲存的設計專案", en: "No saved projects", ja: "保存されたプロジェクトはありません" },
  studioEditing: { zh: "編輯中", en: "Editing", ja: "編集中" },
  studioNew: { zh: "新建", en: "New", ja: "新規" },
  studioOpen: { zh: "開啟", en: "Open", ja: "開く" },
  studioSaveProject: { zh: "儲存設計專案", en: "Save Design Project", ja: "デザインプロジェクトを保存" },
  studioSaveDesc: { zh: "為您的設計專案命名以便日後編輯", en: "Name your project for future editing", ja: "後で編集できるようにプロジェクトに名前を付けてください" },
  studioProjectNamePlaceholder: { zh: "例如：春季促銷廣告", en: "e.g. Spring Promo Ad", ja: "例：春のプロモ広告" },
  studioOpenProject: { zh: "開啟設計專案", en: "Open Design Project", ja: "デザインプロジェクトを開く" },
  studioOpenDesc: { zh: "選擇一個已儲存的專案繼續編輯", en: "Select a saved project to continue editing", ja: "保存されたプロジェクトを選択して編集を続ける" },
  studioProjectSaved: { zh: "專案已儲存", en: "Project saved", ja: "プロジェクトを保存しました" },
  studioProjectSaveFailed: { zh: "儲存失敗", en: "Save failed", ja: "保存に失敗しました" },
  studioProjectLoaded: { zh: "專案已載入", en: "Project loaded", ja: "プロジェクトを読み込みました" },
  studioProjectDeleted: { zh: "專案已刪除", en: "Project deleted", ja: "プロジェクトを削除しました" },
  studioDeleteBoundError: { zh: "無法刪除，此專案已被綁定", en: "Cannot delete, project is in use", ja: "削除できません。プロジェクトは使用中です" },
  studioDeleteBoundSchedule: { zh: "排程", en: "Schedules", ja: "スケジュール" },
  studioDeleteBoundMedia: { zh: "素材", en: "Media", ja: "メディア" },
  studioOverlays: { zh: "重疊區塊", en: "Overlays", ja: "オーバーレイ" },
  studioAddOverlay: { zh: "新增重疊區塊", en: "Add Overlay", ja: "オーバーレイ追加" },
  studioEditOverlay: { zh: "編輯重疊區塊", en: "Edit Overlay", ja: "オーバーレイ編集" },
  studioDeleteOverlay: { zh: "刪除重疊區塊", en: "Delete Overlay", ja: "オーバーレイ削除" },
  studioOverlayHint: { zh: "可自由拖曳移動與調整大小", en: "Drag to move, resize from edges", ja: "ドラッグで移動、端からリサイズ" },
  studioOpacity: { zh: "不透明度", en: "Opacity", ja: "不透明度" },
  studioLayerOrder: { zh: "圖層順序", en: "Layer Order", ja: "レイヤー順序" },
  studioLayerUp: { zh: "上移", en: "Up", ja: "上へ" },
  studioLayerDown: { zh: "下移", en: "Down", ja: "下へ" },
  studioLocked: { zh: "已鎖定位置", en: "Position Locked", ja: "位置ロック中" },
  studioUnlocked: { zh: "鎖定位置", en: "Lock Position", ja: "位置をロック" },

  // Publishing Center
  publishTitle: { zh: "發佈管理", en: "Publishing Center", ja: "配信管理" },
  publishSubtitle: { zh: "將播放清單發佈到指定螢幕，支援立即發佈與預約排程", en: "Publish playlists to target screens with instant or scheduled delivery", ja: "プレイリストを指定スクリーンに即時または予約配信" },
  publishPlaylist: { zh: "播放清單", en: "Playlist", ja: "プレイリスト" },
  publishNoPlaylists: { zh: "尚無播放清單", en: "No playlists available", ja: "プレイリストがありません" },
  publishItems: { zh: "個項目", en: "items", ja: "アイテム" },
  publishTargetScreens: { zh: "目標螢幕", en: "Target Screens", ja: "対象スクリーン" },
  publishSearchScreens: { zh: "搜尋螢幕或群組...", en: "Search screens or groups...", ja: "スクリーンまたはグループを検索..." },
  publishSelectAll: { zh: "全部群組", en: "Select All", ja: "全グループ" },
  publishScreensTotal: { zh: "台螢幕", en: "screens", ja: "台スクリーン" },
  publishScreensSelected: { zh: "台已選取", en: "selected", ja: "台選択済み" },
  publishActions: { zh: "發佈動作", en: "Publish Actions", ja: "配信アクション" },
  publishNotSelected: { zh: "尚未選取", en: "Not selected", ja: "未選択" },
  publishNow: { zh: "立即發佈", en: "Publish Now", ja: "今すぐ配信" },
  publishNowDesc: { zh: "即刻同步至所有目標螢幕", en: "Sync to all target screens immediately", ja: "全対象スクリーンに即時同期" },
  publishScheduled: { zh: "預約發佈", en: "Scheduled Publish", ja: "予約配信" },
  publishScheduledDesc: { zh: "設定未來的日期與時間自動上線", en: "Set a future date and time to go live", ja: "将来の日時を設定して自動配信" },
  publishScheduleDate: { zh: "發佈日期", en: "Publish Date", ja: "配信日" },
  publishPickDate: { zh: "選擇日期", en: "Pick a date", ja: "日付を選択" },
  publishScheduleTime: { zh: "發佈時間", en: "Publish Time", ja: "配信時刻" },
  publishNowBtn: { zh: "立即發佈", en: "Publish Now", ja: "今すぐ配信" },
  publishScheduledBtn: { zh: "預約發佈", en: "Schedule Publish", ja: "予約配信" },
  publishSelectPlaylist: { zh: "請先選擇播放清單", en: "Please select a playlist first", ja: "プレイリストを選択してください" },
  publishSelectScreen: { zh: "請選擇至少一台螢幕", en: "Please select at least one screen", ja: "少なくとも1つのスクリーンを選択してください" },
  publishSelectDate: { zh: "請選擇發佈日期", en: "Please select a publish date", ja: "配信日を選択してください" },
  publishSuccessNow: { zh: "已成功發佈到所有目標螢幕！", en: "Published to all target screens!", ja: "全対象スクリーンに配信しました！" },
  publishSuccessScheduled: { zh: "已預約發佈成功！", en: "Scheduled publish created!", ja: "予約配信を設定しました！" },
  publishSuccessTitle: { zh: "發佈成功！", en: "Published!", ja: "配信完了！" },
  publishSuccessDesc: { zh: "內容已同步至目標螢幕", en: "Content synced to target screens", ja: "コンテンツを対象スクリーンに同期しました" },
  publishRecords: { zh: "發佈紀錄", en: "Publish Records", ja: "配信履歴" },
  publishNoRecords: { zh: "尚無發佈紀錄", en: "No publish records yet", ja: "配信履歴がありません" },
  publishRecordPlaylist: { zh: "播放清單", en: "Playlist", ja: "プレイリスト" },
  publishRecordScreen: { zh: "螢幕", en: "Screen", ja: "スクリーン" },
  publishRecordStatus: { zh: "狀態", en: "Status", ja: "ステータス" },
  publishRecordTime: { zh: "時間", en: "Time", ja: "時刻" },
  publishStatusPlaying: { zh: "播放中", en: "Playing", ja: "再生中" },
  publishStatusScheduled: { zh: "已預約", en: "Scheduled", ja: "予約済み" },
  publishStatusSending: { zh: "傳送中", en: "Sending", ja: "送信中" },
  publishStatusEmergency: { zh: "緊急插播", en: "Emergency", ja: "緊急配信" },
  publishLoading: { zh: "載入中...", en: "Loading...", ja: "読み込み中..." },
  publishUngrouped: { zh: "未分類", en: "Ungrouped", ja: "未分類" },

  // Emergency Broadcast
  emergencyBroadcast: { zh: "緊急插播", en: "Emergency Broadcast", ja: "緊急配信" },
  emergencyTitle: { zh: "重大災害緊急插播", en: "Emergency Broadcast", ja: "緊急災害配信" },
  emergencyDesc: { zh: "此功能將立即覆蓋所有螢幕的當前播放內容，用於重大災害或緊急公告。", en: "This will immediately override all screen content for emergency announcements.", ja: "全スクリーンの現在のコンテンツを即座に上書きします。緊急告知用です。" },
  emergencyWarning: { zh: "請注意以下事項", en: "Please note the following", ja: "以下にご注意ください" },
  emergencyWarning1: { zh: "所有螢幕將立即中斷當前播放內容", en: "All screens will immediately interrupt current playback", ja: "全スクリーンが即座に現在の再生を中断します" },
  emergencyWarning2: { zh: "緊急訊息將覆蓋所有排程與預設播放", en: "Emergency message will override all schedules and default playback", ja: "緊急メッセージが全スケジュールとデフォルト再生を上書きします" },
  emergencyWarning3: { zh: "此操作無法自動還原，需手動恢復正常播放", en: "This action cannot be auto-reversed, manual restore required", ja: "この操作は自動復元できません。手動で復元が必要です" },
  emergencyMessage: { zh: "緊急訊息內容", en: "Emergency Message", ja: "緊急メッセージ内容" },
  emergencyMessagePlaceholder: { zh: "例如：因颱風來襲，本店臨時休業，敬請見諒。", en: "e.g. Due to typhoon, store is temporarily closed.", ja: "例：台風のため臨時休業いたします。" },
  emergencyAffectedScreens: { zh: "影響範圍", en: "Affected Screens", ja: "影響範囲" },
  emergencyAllScreens: { zh: "所有螢幕", en: "All Screens", ja: "全スクリーン" },
  emergencyConfirmBtn: { zh: "確認緊急插播", en: "Confirm Emergency Broadcast", ja: "緊急配信を確認" },
  emergencyDoubleConfirmTitle: { zh: "最終確認", en: "Final Confirmation", ja: "最終確認" },
  emergencyDoubleConfirmDesc: { zh: "確定要對所有螢幕執行緊急插播嗎？此操作將立即生效且無法自動還原。", en: "Are you sure you want to broadcast to ALL screens? This takes effect immediately and cannot be auto-reversed.", ja: "全スクリーンに緊急配信を実行しますか？即座に有効になり自動復元できません。" },
  emergencyExecute: { zh: "執行緊急插播", en: "Execute Emergency Broadcast", ja: "緊急配信を実行" },
  emergencyFillMessage: { zh: "請填寫緊急訊息內容", en: "Please fill in the emergency message", ja: "緊急メッセージを入力してください" },
  emergencyBroadcastSent: { zh: "緊急插播已發送！", en: "Emergency Broadcast Sent!", ja: "緊急配信を送信しました！" },
  emergencyBroadcastSentDesc: { zh: "所有螢幕已收到緊急訊息", en: "All screens have received the emergency message", ja: "全スクリーンが緊急メッセージを受信しました" },

  // Restore Normal Playback
  restoreNormal: { zh: "恢復正常播放", en: "Restore Normal", ja: "通常再生に復帰" },
  restoreNormalTitle: { zh: "恢復正常播放", en: "Restore Normal Playback", ja: "通常再生に復帰" },
  restoreNormalDesc: { zh: "此操作將解除所有螢幕的緊急插播狀態，恢復為正常排程播放。", en: "This will dismiss the emergency broadcast on all screens and restore normal scheduled playback.", ja: "全スクリーンの緊急配信を解除し、通常のスケジュール再生に復帰します。" },
  restoreNormalConfirm: { zh: "確認恢復", en: "Confirm Restore", ja: "復帰を確認" },
  restoreNormalSuccess: { zh: "已恢復正常播放！", en: "Normal Playback Restored!", ja: "通常再生に復帰しました！" },
  restoreNormalSuccessDesc: { zh: "所有螢幕已恢復正常排程播放", en: "All screens have returned to normal scheduled playback", ja: "全スクリーンが通常のスケジュール再生に復帰しました" },
  restoreNormalNoEmergency: { zh: "目前沒有緊急插播中的螢幕", en: "No screens currently in emergency mode", ja: "現在緊急配信中のスクリーンはありません" },

  // Dashboard Emergency
  dashEmergencyTitle: { zh: "⚠️ 緊急插播進行中", en: "⚠️ Emergency Broadcast Active", ja: "⚠️ 緊急配信が進行中" },
  dashEmergencyDesc: { zh: "目前有 {count} 個螢幕正處於緊急插播模式，正常排程已被覆蓋。", en: "{count} screen(s) are currently in emergency broadcast mode. Normal schedules are overridden.", ja: "現在 {count} 台のスクリーンが緊急配信モードです。通常スケジュールは上書きされています。" },
  dashEmergencyAction: { zh: "前往處理", en: "Go to Publishing", ja: "発行管理へ" },

  // Dashboard enhanced
  dashPublishToday: { zh: "今日發佈", en: "Published Today", ja: "本日の配信" },
  dashPublishTodaySub: { zh: "筆發佈紀錄", en: "publish records", ja: "件の配信記録" },
  dashScheduledPending: { zh: "待排程", en: "Scheduled", ja: "予約中" },
  dashScheduledPendingSub: { zh: "筆等待執行", en: "pending execution", ja: "件の実行待ち" },
  dashEmergencyCount: { zh: "緊急插播", en: "Emergency", ja: "緊急配信" },
  dashEmergencyCountSub: { zh: "台螢幕受影響", en: "screens affected", ja: "台が影響中" },
  dashQuickActions: { zh: "快捷操作", en: "Quick Actions", ja: "クイック操作" },
  dashQuickPublish: { zh: "發佈管理", en: "Publishing", ja: "配信管理" },
  dashQuickScreen: { zh: "新增螢幕", en: "Add Screen", ja: "スクリーン追加" },
  dashQuickMedia: { zh: "上傳素材", en: "Upload Media", ja: "メディア追加" },
  dashQuickSchedule: { zh: "排程管理", en: "Schedules", ja: "スケジュール" },
  dashLastRefresh: { zh: "最後更新", en: "Last updated", ja: "最終更新" },
  dashAutoRefresh: { zh: "自動刷新中", en: "Auto-refreshing", ja: "自動更新中" },
  dashWidgetCount: { zh: "個 Widget", en: "widgets", ja: "ウィジェット" },

  // Organization & Team Management
  orgTitle: { zh: "組織管理", en: "Organizations", ja: "組織管理" },
  orgSubtitle: { zh: "管理組織架構與數據隔離", en: "Manage organization structure and data isolation", ja: "組織構造とデータ分離を管理" },
  orgAdd: { zh: "新增組織", en: "Add Organization", ja: "組織を追加" },
  orgName: { zh: "組織名稱", en: "Organization Name", ja: "組織名" },
  orgNamePlaceholder: { zh: "例如：台北分公司", en: "e.g. Taipei Branch", ja: "例：東京支社" },
  orgDescription: { zh: "組織描述", en: "Description", ja: "説明" },
  orgDescriptionPlaceholder: { zh: "簡述組織用途...", en: "Describe the organization...", ja: "組織の説明..." },
  orgCreated: { zh: "組織已建立", en: "Organization created", ja: "組織を作成しました" },
  orgUpdated: { zh: "組織已更新", en: "Organization updated", ja: "組織を更新しました" },
  orgDeleted: { zh: "組織已刪除", en: "Organization deleted", ja: "組織を削除しました" },
  orgDeleteConfirm: { zh: "確定要刪除此組織？所有團隊與成員資料將被移除。", en: "Delete this organization? All teams and members will be removed.", ja: "この組織を削除しますか？全チームとメンバーが削除されます。" },
  orgNoOrgs: { zh: "尚未建立任何組織", en: "No organizations yet", ja: "組織がまだありません" },
  orgTeamCount: { zh: "個團隊", en: "teams", ja: "チーム" },
  orgMemberCount: { zh: "位成員", en: "members", ja: "メンバー" },
  orgFilterAll: { zh: "所有組織", en: "All Organizations", ja: "すべての組織" },

  teamTitle: { zh: "團隊管理", en: "Teams", ja: "チーム管理" },
  teamAdd: { zh: "新增團隊", en: "Add Team", ja: "チームを追加" },
  teamName: { zh: "團隊名稱", en: "Team Name", ja: "チーム名" },
  teamNamePlaceholder: { zh: "例如：行銷部門", en: "e.g. Marketing Dept", ja: "例：マーケティング部" },
  teamOrg: { zh: "所屬組織", en: "Organization", ja: "所属組織" },
  teamSelectOrg: { zh: "選擇組織", en: "Select organization", ja: "組織を選択" },
  teamCreated: { zh: "團隊已建立", en: "Team created", ja: "チームを作成しました" },
  teamUpdated: { zh: "團隊已更新", en: "Team updated", ja: "チームを更新しました" },
  teamDeleted: { zh: "團隊已刪除", en: "Team deleted", ja: "チームを削除しました" },
  teamDeleteConfirm: { zh: "確定要刪除此團隊？所有成員將被移除。", en: "Delete this team? All members will be removed.", ja: "このチームを削除しますか？全メンバーが削除されます。" },
  teamNoTeams: { zh: "尚未建立任何團隊", en: "No teams yet", ja: "チームがまだありません" },
  teamPermissions: { zh: "權限設定", en: "Permissions", ja: "権限設定" },
  teamPermScreens: { zh: "螢幕管理", en: "Screen Management", ja: "スクリーン管理" },
  teamPermMedia: { zh: "素材管理", en: "Media Management", ja: "メディア管理" },
  teamPermSchedules: { zh: "排程管理", en: "Schedule Management", ja: "スケジュール管理" },
  teamPermPublish: { zh: "發佈管理", en: "Publishing", ja: "配信管理" },
  teamPermStudio: { zh: "內容設計", en: "Content Studio", ja: "コンテンツスタジオ" },

  memberAdd: { zh: "新增成員", en: "Add Member", ja: "メンバーを追加" },
  memberRemove: { zh: "移除成員", en: "Remove Member", ja: "メンバーを削除" },
  memberRemoveConfirm: { zh: "確定要將此成員從團隊中移除？", en: "Remove this member from the team?", ja: "このメンバーをチームから削除しますか？" },
  memberAdded: { zh: "成員已加入", en: "Member added", ja: "メンバーを追加しました" },
  memberRemoved: { zh: "成員已移除", en: "Member removed", ja: "メンバーを削除しました" },
  memberAlreadyInTeam: { zh: "此使用者已在團隊中", en: "User already in this team", ja: "このユーザーは既にチームに所属しています" },
  memberSelectUser: { zh: "選擇使用者", en: "Select user", ja: "ユーザーを選択" },
  memberRole: { zh: "團隊角色", en: "Team Role", ja: "チーム役割" },
  memberRoleLeader: { zh: "團隊主管", en: "Team Leader", ja: "チームリーダー" },
  memberRoleMember: { zh: "一般成員", en: "Member", ja: "メンバー" },
  memberNoMembers: { zh: "尚未加入任何成員", en: "No members yet", ja: "メンバーがまだいません" },

  tabUsers: { zh: "使用者", en: "Users", ja: "ユーザー" },
  tabOrgs: { zh: "組織", en: "Organizations", ja: "組織" },
  tabTeams: { zh: "團隊", en: "Teams", ja: "チーム" },
  orgFillRequired: { zh: "請填寫組織名稱", en: "Please fill in organization name", ja: "組織名を入力してください" },
  teamFillRequired: { zh: "請填寫團隊名稱並選擇組織", en: "Please fill in team name and select organization", ja: "チーム名と組織を入力してください" },

  // Tooltip keys
  tipScreen: { zh: "螢幕", en: "Screen", ja: "スクリーン" },
  tipGroup: { zh: "群組", en: "Group", ja: "グループ" },
  tipLocation: { zh: "位置", en: "Location", ja: "設置場所" },
  tipResolution: { zh: "解析度", en: "Resolution", ja: "解像度" },
  tipSerialNumber: { zh: "序號", en: "Serial Number", ja: "シリアル番号" },
  tipIpAddress: { zh: "網路 IP 位址", en: "IP Address", ja: "IPアドレス" },
  tipFirmwareVersion: { zh: "韌體版本", en: "Firmware Version", ja: "ファームウェアバージョン" },
  tipConnectionType: { zh: "連線方式", en: "Connection Type", ja: "接続方式" },
  tipWired: { zh: "有線", en: "Wired", ja: "有線" },
  tipWireless: { zh: "無線", en: "Wireless", ja: "無線" },
  tipNetworkSpeedHealth: { zh: "網路速度健康狀態（閾值：上傳 {up} Mbps / 下載 {down} Mbps）", en: "Network speed health (threshold: upload {up} Mbps / download {down} Mbps)", ja: "ネットワーク速度ヘルス（しきい値：上り {up} Mbps / 下り {down} Mbps）" },
  tipSpeedNotSet: { zh: "未設定", en: "Not set", ja: "未設定" },
  tipAddScreenGroup: { zh: "新增螢幕群組", en: "Add screen group", ja: "スクリーングループを追加" },
  tipAddScreen: { zh: "新增螢幕", en: "Add screen", ja: "スクリーンを追加" },
  tipSpeedThreshold: { zh: "網路速度閾值設定", en: "Network speed threshold settings", ja: "ネットワーク速度しきい値設定" },
  tipIotDevices: { zh: "IoT 擴充裝置", en: "IoT Devices", ja: "IoT デバイス" },
  tipEditScreen: { zh: "編輯螢幕", en: "Edit screen", ja: "スクリーンを編集" },
  tipDeleteScreen: { zh: "刪除螢幕", en: "Delete screen", ja: "スクリーンを削除" },
  tipGridView: { zh: "格狀檢視", en: "Grid view", ja: "グリッド表示" },
  tipListView: { zh: "列表檢視", en: "List view", ja: "リスト表示" },
  tipMoveUp: { zh: "向上移動", en: "Move up", ja: "上に移動" },
  tipMoveDown: { zh: "向下移動", en: "Move down", ja: "下に移動" },
  tipPhoneCall: { zh: "撥打電話", en: "Phone call", ja: "電話をかける" },
  tipVideoCall: { zh: "視訊通話", en: "Video call", ja: "ビデオ通話" },
  tipMoreOptions: { zh: "更多選項", en: "More options", ja: "その他のオプション" },
  tipUploadAttachment: { zh: "上傳附件或照片", en: "Upload attachment or photo", ja: "添付ファイルまたは写真をアップロード" },
  tipUploadImage: { zh: "上傳圖片", en: "Upload image", ja: "画像をアップロード" },
  tipVoiceToText: { zh: "語音轉文字", en: "Voice to text", ja: "音声テキスト変換" },
  tipSendMessage: { zh: "送出訊息", en: "Send message", ja: "メッセージを送信" },
  tipSwitchLanguage: { zh: "切換語言", en: "Switch Language", ja: "言語切替" },
  tipRefresh: { zh: "重新整理", en: "Refresh", ja: "更新" },
  tipSystemSettings: { zh: "系統設定", en: "Settings", ja: "システム設定" },
  tipUndo: { zh: "復原", en: "Undo", ja: "元に戻す" },
  tipRedo: { zh: "重做", en: "Redo", ja: "やり直す" },
  tipBold: { zh: "粗體", en: "Bold", ja: "太字" },
  tipItalic: { zh: "斜體", en: "Italic", ja: "斜体" },
  tipUnderline: { zh: "底線", en: "Underline", ja: "下線" },
  tipStrikethrough: { zh: "刪除線", en: "Strikethrough", ja: "取り消し線" },
  tipTextColor: { zh: "文字顏色", en: "Text Color", ja: "テキスト色" },
  tipAlignLeft: { zh: "靠左對齊", en: "Align Left", ja: "左揃え" },
  tipAlignCenter: { zh: "置中對齊", en: "Align Center", ja: "中央揃え" },
  tipAlignRight: { zh: "靠右對齊", en: "Align Right", ja: "右揃え" },
  tipBulletList: { zh: "項目符號清單", en: "Bullet List", ja: "箇条書き" },
  tipOrderedList: { zh: "編號清單", en: "Ordered List", ja: "番号付きリスト" },
  tipInsertImage: { zh: "插入圖片", en: "Insert Image", ja: "画像を挿入" },
  tipUpdated: { zh: "更新", en: "Updated", ja: "更新" },
  tipUploadFile: { zh: "上傳文件", en: "Upload file", ja: "ファイルをアップロード" },
  tipView: { zh: "檢視", en: "View", ja: "表示" },
} as const;

type TranslationKey = keyof typeof translations;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("signboard-lang");
    return (saved as Language) || "zh";
  });

  useEffect(() => {
    localStorage.setItem("signboard-lang", language);
    document.documentElement.lang = language === "zh" ? "zh-TW" : language === "ja" ? "ja" : "en";
  }, [language]);

  const t = (key: TranslationKey): string => {
    return translations[key]?.[language] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
